#! /bin/sh
### BEGIN INIT INFO
# Provides:          darkhttpd
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: darkhttpd start script
# Description:       this script starts darkhttpd
### END INIT INFO

. /lib/lsb/init-functions

# Globals
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/darkhttpd
NAME=darkhttpd
DESC="web server"
PIDFILE=/var/run/darkhttpd.pid

test -x $DAEMON || exit 0

# Include darkhttpd defaults if available
[ -r /etc/default/darkhttpd ] && . /etc/default/darkhttpd

set -e

if [ "$1" != status ]; then
	# be sure there is a /var/run/darkhttpd, even with tmpfs
	# The directory is defined as volatile and may thus be non-existing
	# after a boot (DPM §9.3.2)
	if ! dpkg-statoverride --list /var/run/darkhttpd >/dev/null 2>&1; then
		install -d -o www-data -g www-data -m 0750 "/var/run/darkhttpd"
	fi
fi

case "$1" in
  start)
	log_daemon_msg "Starting $DESC: "$NAME
	if start-stop-daemon --start --quiet --pidfile $PIDFILE --make-pidfile \
	--background --exec $DAEMON -- $DARKHTTPD_ROOT $DARKHTTPD_FLAGS || true; then
	log_end_msg 0
	else
	log_end_msg 1
	fi
	;;

  stop)
	log_daemon_msg "Stopping $DESC: "$NAME
	if start-stop-daemon --stop --retry 30 --oknodo --quiet \
		--pidfile $PIDFILE --exec $DAEMON
	then
		rm -f $PIDFILE
		log_end_msg 0
	else
		log_end_msg 1
	fi
	;;

  restart|force-reload)
	$0 stop
	sleep 2
	$0 start
	;;

  status)
	status_of_proc -p "$PIDFILE" "$DAEMON" darkhttpd && exit 0 || exit $?
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
	exit 1
	;;
esac

exit 0
