#!/bin/sh

set -e

case "$1" in
    configure)
        if ! getent passwd www-data > /dev/null; then
            adduser --system --disabled-password --disabled-login --home /var/www-data \
                    --quiet --force-badname --group www-data
        fi
	if [ ! -e /var/www/darkhttpd/index.* ] ; then
		mkdir -p /var/www/darkhttpd
		cp /usr/share/darkhttpd/index.html /var/www/darkhttpd/index.html
	fi
        ;;
esac

#DEBHELPER#

exit 0

